version: "3.9"

services:
  python-dev:
    build:
      context: ${VIRTUAL_ENV}/devops-shared-data
      dockerfile: docker-files/python-dev/Dockerfile
    image: python-dev:latest
    extra_hosts:
      host.docker.internal: host-gateway
      # require a tunnel on host
    # definition explicite
    # env_file: env/.env
    environment:
        # to have poetry and pypi credentials inside dev container do not forget to set
        # before running docker-compose up
        RUN_TIME_ENV:
    network_mode: host
    restart: always
    depends_on:
      - debian-base
